#This file is based on code from https://plot.ly/~colleenV/6/twitter-vs-facebook/#code
#This code creates a pie chart to show what percentage of my total facebook likes are generated by posts on each day

import plotly.plotly as py
from plotly.graph_objs import *
import sqlite3
import datetime
import calendar


conn=sqlite3.connect('206_Final.sqlite')
cur=conn.cursor()

rows=cur.execute('Select likes, time_posted from Facebook')

days={} #Dictionary to keep track of likes from each post on each day
total_likes=0 #Accumulator to keep track of total likes from Facebook posts

for row in rows:
	likes=int(row[0]) #Ensures likes are represented by integer values

	date_time=str(row[1]).split('T') #Splits timestamp into date and time
	date=datetime.datetime.strptime(date_time[0], '%Y-%M-%d') #Creates datetime object by stripping date 
	day=datetime.datetime.weekday(date) #Gets numerical value for day of the week Monday is 0, Sunday is 6
	
	if day not in days: #Accumulates total likes for each day inside dictionary days
		days[day]=likes
	else:
		days[day]+=likes
	
	total_likes+=likes #Accumulates total likes across all days

x=[]
y=[]

for day in sorted(days.keys()): #Sorts days of week Monday-Sunday
	(key, value)=(calendar.day_name[day], days[day]/total_likes) #Converts numerical day value into word, divides total likes for individual days by total likes for all days
	#Creates tuples of day of the week and average likes for posts posted on that day
	x.append(key) #Separates tuple into two separate lists for the labels and their relevant values
	y.append(value)

py.sign_in('alkahan', 'vdr8fzFddzEuRqqABNzQ') 
trace1 = {  
  "labels": x, 
  "values": y, 
  "name": "Facebook", 
  "type": "pie"
}

data = Data([trace1])
layout = {"barmode": "group",
'title':'Facebook Percent Likes Per Day',
}

fig = Figure(data=data, layout=layout) 

plot_url = py.plot(fig)

cur.close()